# app_config.toml

[graphql]
debug = true

[uvicorn]
host = "localhost"
port = 8080
log_level = "info"
access_log = true
reload = true
workers = 4

[postgres]
host = "localhost"
port = 7070
user = "postgres"
password = "postgres"
database = "rik_app"
timeout = 5
command_timeout = 10

[cors]
origins = [
    "http://localhost:6060"
]
