# app_config.toml

[graphql]
schema_file_name = "schema.graphql"
debug = true

[postgres]
host = "localhost"
port = 5432
username = "postgres"
password = "postgres"

[uvicorn]
host = "localhost"
port = 8080
log_level = "info"
access_log = true
reload = true
workers = 4
